# Generated by Django 4.1.7 on 2023-03-20 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='filesUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file_uploaded', models.FileField(upload_to='csv_or_excel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])])),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
